# Generated by Django 5.0.5 on 2024-05-07 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_id', models.IntegerField()),
                ('partner_id', models.IntegerField()),
                ('date', models.DateField()),
                ('received_time', models.DateTimeField()),
                ('converted_textfile', models.TextField()),
                ('recorded_audiofile', models.TextField()),
                ('converted_textfile_piece', models.TextField()),
                ('recorded_audiofile_piece', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AI_User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('profile_img', models.ImageField(upload_to='ai_user_profile_images/')),
                ('description', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakietalkie.language')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('profile_img', models.ImageField(upload_to='user_profile_images/')),
                ('description', models.TextField()),
                ('want_language', models.CharField(max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakietalkie.language')),
            ],
        ),
    ]
