# Generated by Django 4.2.13 on 2024-06-07 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AI_User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=100)),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="ai_user_profile_images/"
                    ),
                ),
                ("ai_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("ai_partner_id", models.IntegerField()),
                ("date", models.CharField(max_length=20)),
                ("calling_time", models.CharField(max_length=20)),
                ("converted_text_file", models.CharField(max_length=100)),
                ("recorded_audio_file", models.CharField(max_length=100)),
                ("language", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="VocabList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("recording_id", models.IntegerField()),
                ("date", models.CharField(max_length=20)),
                ("word_list", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=100)),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_profile_images/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wakietalkie.language",
                    ),
                ),
                (
                    "want_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wanted_by",
                        to="wakietalkie.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wakietalkie.ai_user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ai_user",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wakietalkie.language"
            ),
        ),
    ]
